site_name: WebHook-Gateway Documentation
docs_dir: doc
repo_url: https://github.com/deuill/webhook-gateway
edit_uri: edit/trunk/
theme:
  name: readthedocs
nav:
  - Introduction: README.md
  - Sources:
      - Grafana: pkg/source/grafana/README.md
      - Cloudflare Notifications: pkg/source/cloudflare-notifications/README.md
  - Destinations:
      - XMPP: pkg/destination/xmpp/README.md
      - IRC: pkg/destination/irc/README.md
